# Demo of some `numpy` features

## MCS 275 Spring 2024 - David Dumas

This is a quick tour of some `numpy` features.  For more detail see:
* [Chapter 2 of VanderPlas](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
* [The numpy documentation](https://numpy.org/doc/stable/)

## Importing the module

And checking the version.

In [1]:
import numpy as np
print(np.__version__)

1.21.5


## Creating arrays

They are iterable and type-homogeneous.  Can make one from any suitable iterable.

[List of built-in dtypes](https://numpy.org/doc/stable/reference/arrays.scalars.html#arrays-scalars-built-in).

In [2]:
x = np.array( [1,2,5,91,0.25] )

In [3]:
x

array([ 1.  ,  2.  ,  5.  , 91.  ,  0.25])

In [4]:
long_vector = np.array(range(10000))  # notice we can pass any iterable

In [5]:
print(long_vector)

[   0    1    2 ... 9997 9998 9999]


In [9]:
A = np.array( 
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check number of dimensions

In [10]:
x.ndim

1

In [11]:
A.ndim

2

Check shape (size in each dimension)

In [13]:
x

array([ 1.  ,  2.  ,  5.  , 91.  ,  0.25])

In [12]:
x.shape

(5,)

In [14]:
(4,5,6)  # tuple with three items
(8)      # grouping parens -- integer 8
(8,)     # tuple with only one item

(8,)

In [15]:
#How many elements does the vector `x` have?
x.shape[0]  # the first, and only, number in the shape tuple

5

Check "length" (first elt of shape)

In [16]:
len(x)

5

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A.shape

(3, 3)

In [19]:
len(A)   # how many ROWS does this matrix have

3

In [21]:
B = np.array(
[
    [1,7],
    [3,4],
    [9,-2],
    [0,0],
    [5,1]
])

In [22]:
B.ndim

2

In [23]:
B.shape

(5, 2)

In [24]:
len(B)

5

Check data type

In [25]:
x

array([ 1.  ,  2.  ,  5.  , 91.  ,  0.25])

In [26]:
x.dtype

dtype('float64')

Data type typically inferred but can be specified (potential lossy process)

In [27]:
y = np.array( [6,7,6,0,6,-2,6,1], dtype="float64" )

In [29]:
print(y)
print(y.dtype)

[ 6.  7.  6.  0.  6. -2.  6.  1.]
float64


In [30]:
y = np.array( [6,7,6,0,6,-2,6,1] )

In [31]:
print(y)
print(y.dtype)

[ 6  7  6  0  6 -2  6  1]
int64


In [32]:
# uint8 - unsigned integer of size 8 bits
# i.e. minimum value is 0, maximum value is 255
np.array( [ 1, 2, -4, 16, 32, 128, 256, 512, 2000], dtype="uint8")

array([  1,   2, 252,  16,  32, 128,   0,   0, 208], dtype=uint8)

In [33]:
2000 % 256

208

Can make a 2D array (matrix) from a list of lists

## Filled arrays

Can fill with zeros, ones, or make an array full of a general value.

In [34]:
np.zeros( 8 )

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros( 15, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros( 10, dtype="bool")

array([False, False, False, False, False, False, False, False, False,
       False])

In [37]:
np.zeros( (5,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros( (2,7,5) )

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [40]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [41]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.full((4,5), 5.1)

array([[5.1, 5.1, 5.1, 5.1, 5.1],
       [5.1, 5.1, 5.1, 5.1, 5.1],
       [5.1, 5.1, 5.1, 5.1, 5.1],
       [5.1, 5.1, 5.1, 5.1, 5.1]])

Can also ask for an array filled with random values (floats between 0 and 1, never exactly 1, uniformly distributed).  Note `np.random` is a submodule, you want `np.random.random(...)`

In [44]:
# `np.random.random(shape)`
np.random.random( (4,2) )

array([[0.79926585, 0.89382772],
       [0.50302303, 0.98457381],
       [0.27077502, 0.5383192 ],
       [0.88353585, 0.09694709]])

In [45]:
np.random.random(2)

array([0.719524 , 0.5997997])

## Special things about 2D arrays

Identity (eye-dentity) matrix

Transpose

## Vector algebra

In [46]:
v = np.array([1,5,7])
w = np.array([-2,-1,1])
u = np.array([3,0,8])

Dot product (and vector length)

In [48]:
v.dot(w) # rutern 1*(-2) + 5*(-1) + 7*1 = 0

0

In [49]:
u.dot(v)

59

In [51]:
np.dot(v,w)  # same as v.dot(w)

0

In [52]:
v.dot(v)  # length squared
v.dot(v) ** 0.5

8.660254037844387

Scalar multiplication

In [53]:
v

array([1, 5, 7])

In [54]:
10*v

array([10, 50, 70])

In [55]:
-2*v

array([ -2, -10, -14])

In [56]:
1.25 * v

array([1.25, 6.25, 8.75])

Elementwise sum

In [57]:
v

array([1, 5, 7])

In [58]:
w

array([-2, -1,  1])

In [59]:
v+w

array([-1,  4,  8])

Elementwise product (?!)

In [60]:
v*w

array([-2, -5,  7])

## Arithmetic progressions

* `np.arange` is `start`, `stop`, `step`
* `np.linspace` is `first`,`last`,`number`

In [61]:
list(range(5,20,2))

[5, 7, 9, 11, 13, 15, 17, 19]

In [62]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
np.arange(5,20,1.5)

array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. , 18.5])

In [65]:
np.arange(0.1,0.2,0.015)

array([0.1  , 0.115, 0.13 , 0.145, 0.16 , 0.175, 0.19 ])

## Accessing items

0-based index

In [66]:
x

array([ 1.  ,  2.  ,  5.  , 91.  ,  0.25])

In [70]:
x[0]

1.0

In [67]:
x[3]  # item at index 3

91.0

In [68]:
for t in x:
    print(t,"is one of the components of the vector")

1.0 is one of the components of the vector
2.0 is one of the components of the vector
5.0 is one of the components of the vector
91.0 is one of the components of the vector
0.25 is one of the components of the vector


Multidimensional indexing: use a tuple of indices

In [71]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
#A[rownumber, columnnumber]
A[2,1]

8

Omitted indices at the end mean "everything from those dimensions"

Using `:` as an index means "everything from that dimension"

## Assigning items

**`numpy` arrays are mutable** 😱

## Slices

Can combine slice notation with multiple indices.

Slices return **views**, not copies.

## Equality and bool

`.all()` checks if an array of booleans is all `True`.

## Ufuncs

Functions that automatically apply to each entry in an array.

### Some arrays to operate on

### Examples of numpy ufuncs

Let $f(x) = 3x^2 - 8x + 14$.  Apply $f$ to each element of array `v`.

## Broadcasting

## Aggregations

`sum`, `max`, `min`, `argmax`, `argmin`, `mean`, `all`, `any`, `array_equal`

## Masks

## Pillow integration

* `np.array(img)` just works, if `img` is a `PIL.Image` object
* Use `PIL.Image.fromarray(A)` to make an image from an array
    * Shape `(height,width)` and dtype `uint8` for grayscale
    * Shape `(height,width,3)` and dtype `uint8` for color (last axis is red, green, blue)